### ISSUE TITLE
output fraction of radar at a range of thresholds

### ISSUE THREAD

**Issue by stevehadd** [informatics-lab/precip_rediagnosis#30]
instantaneous and 3hr accumulation, then spatially aggregated. by taking fraction greater than various thresholds.

**Comment by stevehadd** [comment]
possibly use IMPROVER threshold variables. @arh89 to supply thresholds.

**Comment by stevehadd** [comment]
Here are the improver thresholds:
{
    "0.0": [0.0, 0.0],
    "0.03": [0.027, 0.033],
    "0.09": [0.081, 0.099],
    "0.1": [0.09, 0.11],
    "0.25": [0.225, 0.275],
    "0.3": [0.27, 0.33],
    "0.5": [0.45, 0.55],
    "1.0": [0.9, 1.1],
    "2.0": [1.8, 2.2],
    "3.0": [2.7, 3.3],
    "4.0": [3.6, 4.4],
    "8.0": [7.2, 8.8],
    "12.0": [10.8, 13.2],
    "16.0": [14.4, 17.6],
    "20.0": [18.0, 22.0],
    "25.0": [22.5, 27.5],
    "30.0": [27.0, 33.0],
    "40.0": [36.0, 44.0],
    "50.0": [45.0, 55.0],
    "75.0": [67.5, 82.5],
    "100.0": [90.0, 110.0],
    "150.0": [135.0, 165.0],
    "200.0": [180.0, 220.0]
}

**Comment by stevehadd** [comment]
Looking at how to do this in iris today, there doesn't seem to be an easy way to do this. Proposed steps (which I'm writing here to remind myself) are:
* make a copy of the data ```rain_bands_cube = iris.cube.copy.deepcopy(radar_agg)```
* add a dim coord for rain bands (like the coordinate for realisation)  ```rain_bands_cube.add_dim_coord(
    iris.coords.DimCoord(
        points=[float(v1) for v1 in improver_thresholds.keys()], 
        bounds=list(improver_thresholds.values())))```
* it may be necessary to add a coord to the data first, not sure how?
* iterate through bands, finding grid squares inside the band ``` ((radar_agg.data.data > improver_thresholds['1.0'][0]) & (radar_agg.data.data < improver_thresholds['1.0'][1]))[10,:,:]```, and assigning each one to the relevant spot along the rainband dimension
* copy the target cube (mogreps-g)
* for each time, iterate through the grid squares
* for each grid square, find the source (radar) grid sqquares insides the target grid. Count how many are in the rain band. Assign that value to the copy of the target.
* Do for all times. The new cube will represent fraction of grid square within accumulation band.
* THis is then a new feature to 
We should also follow the same procedure for finding the max radar rainfall in a mogreps-g grid square, as there doesn't seem to be a good way to regrid obtaining the maximum value.

((radar_agg.data.data > improver_thresholds['1.0'][0]) & (radar_agg.data.data < improver_thresholds['1.0'][1]))[10,:,:].sum()

**Comment by arh89** [comment]
@stevehadd I wonder if it might be possible to use some of the IMPROVER code to do this?

e.g: Could use the [improver threshold code](https://github.com/metoppv/improver/blob/master/improver/cli/threshold.py) and then maybe some of the [neighbourhood processing code](https://github.com/metoppv/improver/blob/master/improver/cli/nbhood.py) might do what you want?

(There are a lot of options there, so there might be something that does want you want)

**Comment by stevehadd** [comment]
The improver levels have proved to be a bit difficult to work with, so we're going to instead have a go with fewer rain bands. We're going to use level suggested by Steve Ramsdale from the Forecasters hand book.
* slight < 0.5mm
* moderate 0.5mm - 4.0mm 
* heavy > 4.0mm
