### ISSUE TITLE
Review of extract code 

### ISSUE THREAD

**Issue by hannahbrown7** [informatics-lab/precip_rediagnosis#79]
Main things:
- End dates seem to be inconsistent for Oct 2020 and Oct 2021 amber warnings events. The end date in the file name is the last timestep, in all the others it is the second from last. This seems to be consistent with the last dates in the files for both cases, so may be where last date is missing or sometimes the extract is inclusive, sometimes exclusive? I can't see what in the code would cause this. Not a massive issue, but makes it a bit more difficult to use event configs to reload the data. Maybe even less of a problem once using datasets on AzureML. 
- drivers.py lines 299-301 and lines 302/303 -  same merge repeated twice
- It might be good to remove specific dates from template file and just include format expected  "YYYY-MM-DDTHH:mm:ssZ" 

Minor things:
- drivers.py line 289 f-string missing curly brackets around vars1
- drivers.py line 344 - function not being called with arguments, may just need to be removed
- drivers.py line 101/102 repeated

**Comment by stevehadd** [comment]
Changes made on branch [prd79_data_prep_review](https://github.com/informatics-lab/precip_rediagnosis/tree/prd79_data_prep_review)

> Main things:
> 
> * End dates seem to be inconsistent for Oct 2020 and Oct 2021 amber warnings events.
I believe this was because I had updated the code to ensure the last timestep in the dataset aligned with the end time in the config file 
> * drivers.py lines 299-301 and lines 302/303 -  same merge repeated twice
I've removed the duplicated lines.
> * It might be good to remove specific dates from template file and just include format expected  "YYYY-MM-DDTHH:mm:ssZ"

Good idea, I've update the template file. 
> Minor things:
> 
> * drivers.py line 289 f-string missing curly brackets around vars1
Fixed.
> * drivers.py line 344 - function not being called with arguments, may just need to be removed
Suprious line of code removed.
> * extract_data.py line 101/102 repeated
Repeat removed
