### ISSUE TITLE
Issue with mounting data on GPU cluster

### ISSUE THREAD

**Issue by hannahbrown7** [informatics-lab/precip_rediagnosis#89]
When trying to run hyperdrive on a GPU compute cluster using workaround for issue #84 (mounting dataset then loading data from csv files), I run into error: BFSMountError: Unable to mount blob fuse file system

**Comment by hannahbrown7** [comment]
This error does not seem to occur on a CPU cluster

**Comment by stevehadd** [comment]
Next step is to check this works on the fractional precip modelling branch with cpu and gpu clusters.
